@startuml
skinparam linetype ortho
actor System as CDN
actor User
rectangle TryOnStyleHub {
  usecase "Render/Encode kết quả Try-On" as UC_TryOn_Render
}
UC_TryOn_AI --> UC_TryOn_Render
User --> UC_TryOn_Render
CDN --> UC_TryOn_Render
note right of UC_TryOn_Render
Post: Ảnh được encode phù hợp, upload S3, cung cấp URL truy cập
Exceptions: 500 CDN_UPLOAD_FAILED
end note
@enduml

