@startuml
left to right direction
rectangle "Hệ thống TryOnStyleHub" {
  rectangle "Tải ảnh/Body scan - chi tiết" {
    usecase "Tải ảnh" as Upload_Image
    usecase "Lưu trữ CDN" as Upload_CDNStore
    Upload_Image --> Upload_CDNStore
  }
}
rectangle "Hệ thống tích hợp" {
  actor "Lưu trữ hình ảnh/CDN" as actorCDN
}
Upload_CDNStore ..> actorCDN
@enduml
